from rest_framework.serializers import ModelSerializer
from ..models import Processo

class PostSerializer(ModelSerializer):
  class Meta:
    model = Processo
    fields = (
        'data_cadastro',
        'valor_estimado',
        'valor_contingencia',
        'valor_causa',
        'valor_pedido',
        'valor_risco_provavel',
        'numero_processo',
        'advogado_adverso',
        'advogado_agressor',
        'advogado_colaborador',
        'numero_dossie',
        'pasta_antiga',
        'coligacao',
        'tipo_de_acao',
        'obj_padrao',
        'data_estimada_prevista',
        'data_estimada_pagamento',
        'valor_risco',
        'risco',
        'total_pago',
        'inss_empresa',
        'honorarios',
        'custas_processuais',
        'situacao',
        'nome_desdobramento',
        'data_ajuizamento',
        'ult_desdobramento',
        'instancia',
        'rito',
        'juizo',
        'orgao',
        'comarca',
        'uf',
        'numero',
        'cliente',
        'condicao_cliente',
        'parte_adversa',
        'condicao_adversa',
        'cpf_cnpj_adversa',
        'autor_contumaz',
        'motivo_desligamento',
        'cargo',
        'terceiro_interessado',
        'terceiro',
        'terceiro_prestador',
        'cpf_cnpj_terceiro_prestador',
        'advogado_credenciado',
        'handle_perito',
        'perito',
        'data_encerramento',
        'motivo_encerramento',
        'exito',
        'id_benner',
        'data_evento',
        'evento',
        'tarefas',
        'advogado_centralizador',
        'valor_risco_remoto',
        'observacao',
        'data_atualizacao',
    )