# Generated by Django 4.2.5 on 2023-10-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processo",
            name="tribunal",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
