# Generated by Django 4.2.5 on 2023-11-01 16:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_processo_dano_materia_processo_dano_moral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advogado_nome', models.CharField(max_length=100, null=True)),
                ('advogado_oab', models.CharField(max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='O número da OAB deve estar no formato correto (UFXXXX). Exemplo: AB1234.', regex='^\\d{4,6}/\\w+$')])),
            ],
        ),
        migrations.RemoveField(
            model_name='processo',
            name='advogado_nome',
        ),
        migrations.AlterField(
            model_name='processo',
            name='advogado_oab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='app.advogado'),
        ),
    ]
