# Generated by Django 4.2.5 on 2023-11-01 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_advogado_remove_processo_advogado_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='advogado_nome',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='processo',
            name='advogado_oab',
            field=models.CharField(max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='O número da OAB deve estar no formato correto (UFXXXX). Exemplo: AB1234.', regex='^\\d{4,6}/\\w+$')]),
        ),
        migrations.DeleteModel(
            name='Advogado',
        ),
    ]
