# Generated by Django 4.2.5 on 2023-11-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_processo_advogado_nome_alter_processo_advogado_oab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='advogado_oab',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
